name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 881490135288.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push User service
        run: |
          docker build -t user-service ./user-service
          docker tag user-service:latest 881490135288.dkr.ecr.eu-north-1.amazonaws.com/user-service:latest
          docker push 881490135288.dkr.ecr.eu-north-1.amazonaws.com/user-service:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment --environment-name transaction-service-green --version-label v1.0.0
